### ISSUE TITLE
Feature Request: Manually set thresholds

### ISSUE THREAD

**Issue by agabellini** [DE-IBH/cmk_cisco-dom#4]
I'm using this plugin to monitor some interfaces with the X2 converter (cvr-x2-sfp10g ). Specially I'm using some CWDM optics into this converter. The converter is marked as LR so the  thresholds are those of a LR optics, but the CWDM optics have different ones. The result is a warning or a critical alarm. Is it possible to add a feature to manually set thresholds?

**Comment by liske** [comment]
We have similar setups and you are right, those transceivers are ER and not LR. I would expect that you have repeating errors in the switch's log due to threshold violation:

```
 %SFF8472-5-THRESHOLD_VIOLATION: x/y: Tx power high warning; Operating value:   1.3 dBm, Threshold value:   0.4 dBm.
```

Since this plugin uses the thresholds from the SNMP MIB there is nothing we can do here. The transceiver needs to be reprogrammed (raise an RMA) to report the correct thresholds to IOS - `show int x/y transceiver detail` should report sane optical power values.
